// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/oms/v1/baskets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all baskets from database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basket"
                ],
                "summary": "Get all baskets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new basket.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basket"
                ],
                "summary": "Create basket",
                "parameters": [
                    {
                        "description": "Basket create payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BasketCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/baskets/:basket_id/symbols/:symbol/fill": {
            "post": {
                "description": "Fill basket symbol with fill data",
                "tags": [
                    "Execution"
                ],
                "summary": "Fill basket symbol",
                "responses": {}
            }
        },
        "/oms/v1/baskets/{basket_id}/execute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Execute a basket with specified parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Execute basket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Basket ID",
                        "name": "basket_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Basket execute payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BasketExecuteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/baskets/{basket_id}/execute-sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all execute sessions for a specific basket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "List basket execute sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Basket ID",
                        "name": "basket_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/baskets/{basket_id}/execute/{execution_id}/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all user orders belonging to a specific execution session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Get user orders by execution session ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Basket ID",
                        "name": "basket_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Execution Session ID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/baskets/{basket_id}/execute/{execution_id}/update-price": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update order_price for all orders in session using bid01/bid02/bid03/ask01/ask02/ask03/mid from latest orderbook",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Update all order prices in execution session by price level",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Basket ID",
                        "name": "basket_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Execution Session ID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Price level: bid01, bid02, bid03, ask01, ask02, ask03, mid, ceil, floor",
                        "name": "price_level",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/baskets/{basket_id}/executions/{execution_id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancel a specific execution session by setting status to canceled",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Execution"
                ],
                "summary": "Cancel basket execution session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Basket ID",
                        "name": "basket_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Execution ID",
                        "name": "execution_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/baskets/{basket_id}/executions/{execution_id}/match": {
            "post": {
                "description": "Fill all basket execution with match data",
                "tags": [
                    "Execution"
                ],
                "summary": "Fill all basket execution",
                "responses": {}
            }
        },
        "/oms/v1/baskets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a basket by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basket"
                ],
                "summary": "Get basket detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Basket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing basket. All fields are optional, only provided fields will be updated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "basket"
                ],
                "summary": "Update basket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Basket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Basket update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BasketUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft delete a basket by updating status to removed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basket"
                ],
                "summary": "Delete basket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Basket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/credential-groups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all credential groups belonging to the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Get credential groups by user ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new credential group with multiple credentials (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create credential group",
                "parameters": [
                    {
                        "description": "create credential group payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CredentialGroupCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/credential-groups/{group_id}/credentials": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all credentials belonging to a specific credential group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Get all credentials by group ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Credential Group ID",
                        "name": "group_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/credentials": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all login credentials (Admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get all login credentials",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new login credential with group assignments (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create login credential",
                "parameters": [
                    {
                        "description": "Credential create payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CredentialCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/credentials/{credential_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing login credential (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Update login credential",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Credential ID",
                        "name": "credential_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Credential update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CredentialUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft delete a credential by updating status to disabled (Admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Delete credential",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Credential ID",
                        "name": "credential_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/credentials/{credential_id}/groups": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all groups that a specific credential is assigned to (Admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get all groups by credential ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Credential ID",
                        "name": "credential_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/market/price/{symbol}": {
            "get": {
                "description": "Get bid1-3, ask1-3, mid, ceil, floor for a symbol from latest orderbook",
                "tags": [
                    "market"
                ],
                "summary": "Get price info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Price level: bid1, bid2, bid3, ask1, ask2, ask3, mid, ceil, floor (empty = all)",
                        "name": "price_level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.PriceInfo"
                        }
                    }
                }
            }
        },
        "/oms/v1/orders/{order_id}/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update order_price using bid01/bid02/bid03/ask01/ask02/ask03/mid/ceil/floor from latest orderbook",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Update order price by price level",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Price level: bid01, bid02, bid03, ask01, ask02, ask03, mid, ceil, floor",
                        "name": "price_level",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.DefaultResponseModel"
                        }
                    }
                }
            }
        },
        "/oms/v1/ping": {
            "get": {
                "description": "Welcome route",
                "tags": [
                    "ping"
                ],
                "summary": "Ping route",
                "responses": {}
            }
        },
        "/oms/v2/ping": {
            "get": {
                "description": "Welcome route",
                "tags": [
                    "ping"
                ],
                "summary": "Ping route",
                "responses": {}
            }
        }
    },
    "definitions": {
        "controller.PriceInfo": {
            "type": "object",
            "properties": {
                "ask1": {
                    "type": "number"
                },
                "ask2": {
                    "type": "number"
                },
                "ask3": {
                    "type": "number"
                },
                "bid1": {
                    "type": "number"
                },
                "bid2": {
                    "type": "number"
                },
                "bid3": {
                    "type": "number"
                },
                "ceil": {
                    "type": "number"
                },
                "floor": {
                    "type": "number"
                },
                "mid": {
                    "type": "number"
                }
            }
        },
        "handlers.BasketCreateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "hedge_config": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BasketHedgeConfig"
                    }
                },
                "info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BasketInfo"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.BasketUpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "hedge_config": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BasketHedgeConfig"
                    }
                },
                "info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BasketInfo"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.CredentialCreateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.GroupAssignItem"
                    }
                },
                "info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CredentialInfo"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.CredentialGroupCreateRequest": {
            "type": "object",
            "properties": {
                "credentials": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.CredentialItem"
                    }
                },
                "email": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                }
            }
        },
        "handlers.CredentialItem": {
            "type": "object",
            "properties": {
                "cash_limit": {
                    "type": "number"
                },
                "credential_id": {
                    "type": "string"
                }
            }
        },
        "handlers.CredentialUpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CredentialInfo"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.GroupAssignItem": {
            "type": "object",
            "properties": {
                "cash_limit": {
                    "type": "number"
                },
                "group_id": {
                    "type": "string"
                }
            }
        },
        "models.BasketExecuteRequest": {
            "type": "object",
            "properties": {
                "action_type": {
                    "$ref": "#/definitions/typing.ActionType"
                },
                "credential_id": {
                    "type": "string"
                },
                "future_size": {
                    "type": "number"
                },
                "price_level": {
                    "$ref": "#/definitions/typing.PriceLevel"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "models.BasketHedgeConfig": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "number"
                },
                "size": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "symbol_type": {
                    "$ref": "#/definitions/typing.SymbolType"
                }
            }
        },
        "models.BasketInfo": {
            "type": "object",
            "properties": {
                "cash": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.CredentialInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.DefaultResponseModel": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Use interface{} to allow any type for data"
                },
                "message": {
                    "type": "string"
                },
                "page": {
                    "description": "The pagination information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Pagination"
                        }
                    ]
                },
                "status_code": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.Pagination": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "typing.ActionType": {
            "type": "string",
            "enum": [
                "B",
                "S"
            ],
            "x-enum-varnames": [
                "ActionBuy",
                "ActionSell"
            ]
        },
        "typing.PriceLevel": {
            "type": "string",
            "enum": [
                "mid",
                "ask01",
                "ask02",
                "ask03",
                "bid01",
                "bid02",
                "bid03",
                "ceil",
                "floor"
            ],
            "x-enum-varnames": [
                "PriceLevelMid",
                "PriceLevelAsk01",
                "PriceLevelAsk02",
                "PriceLevelAsk03",
                "PriceLevelBid01",
                "PriceLevelBid02",
                "PriceLevelBid03",
                "PriceLevelCeil",
                "PriceLevelFloor"
            ]
        },
        "typing.SymbolType": {
            "type": "string",
            "enum": [
                "VnStock",
                "VnFuture"
            ],
            "x-enum-varnames": [
                "VnStock",
                "VnFuture"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
